site_url: https://www.marquezamo.com/
logo_url: https://www.marquezamo.com/img/icon.png

backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

i18n:
  structure: single_file
  locales: [en, es]
  default_locale: es

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Datos de la página'
    name: 'site'
    i18n: true
    files:
      - label: 'Información'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        i18n: true
        fields:
          - {
              label: Nombre de la web,
              name: sitename,
              widget: string,
              hint: 'This is used for the site title',
              i18n: true,
            }
          - {
              label: Descripción de la clínica,
              name: sitedescription,
              widget: string,
              hint: 'Describe la clínica',
              i18n: true,
            }
          - { label: Dirección física, name: siteaddress, widget: string, hint: 'calle...', i18n: duplicate }
          - { label: Teléfono, name: sitephone, widget: string, hint: '91...', i18n: duplicate }
          - { label: Correo electrónico, name: siteemail, widget: string, hint: 'nombre@example.com', i18n: duplicate }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Project Category',
          name: 'category',
          widget: 'select',
          default: 'animals',
          options: [{ label: 'Animals', value: 'animals' }, { label: 'Food', value: 'food' }],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
